### ISSUE TITLE
Too many pre-requisites / assumptions

### ISSUE THREAD

**Issue by honir** [frozensheep/rightmoveADF#2]
I was very excited when I found this class, but after 2 wasted hours trying to install it I've given up.
1. Has a (unspecified) dependency of your other library ("synthesize")
2. Assumes use of "composer"
3. Requires an autoloader to have been defined (and with this specific path/classes)
4.  Your code
        `class RightmoveADF {
       use Synthesizer;`
   generates an "invalid T_USE" error (invalid scope)

The nail in the coffin (for me), your Synthesizer class uses traits which means PHP >= 5.4. I wish you'd said that up front.

Thanks for trying and for making it available (even though I personally can't use it)

**Comment by Sam-R** [comment]
@honir - While I understand your frustrations getting this code working (I am having problems myself), I think it might have been more appropriate to raise issues asking for help. I really appreciate that the author has bothered to make the code open source allowing a head start to my own development work. Keep in mind it's an open source project so if you want to make improvements (even if just the read me) you're able to update the code and submit a pull request.
